version: "3.8"

services:
    db:
        build:
            context: .
            dockerfile: db_Dockerfile
    api:
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        expose:
            - 3000
    web:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
